Host: https://cloudlinux.atlassian.net

Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxx

GET /rest/api/2/issue/KPT-409/transitions 

POST /rest/api/2/issue/KPT-409/transitions 
{
    "transition": {
        "id": "31"
    }
}



# Get assets group OR get all servers binded by kernelcare key
Host: https://cln.cloudlinux.com

GET /api/kcare/patchset.json?key=8rrT9NprTW9QfSta

# Get asset CVEs from CLN

Host: https://patches.kernelcare.com/

GET /3d8ff462dd81240ff301b70927a41d4f0e79c14d/10/kpatch.info

Host: https://qualysapi.qg3.apps.qualys.com/

Authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxx

User-Agent: Curl Simple
X-Requested-With: curl app


POST /api/2.0/fo/qid/search_list/dynamic/ action=create title=CVE-Search global=1 cve_ids=CVE-2018-1094

# Create dynamyc search by CVE

POST /api/2.0/fo/qid/search_list/dynamic/ action=create title=CVE-Search global=1 cve_ids=CVE-2018-1094

# Get all QIDs for CVE

GET /api/2.0/fo/qid/search_list/dynamic/ action=list ids=3034146

# Mark QIDs for asset as ignored

GET /msp/ignore_vuln.php qids=157849 ips=54.93.87.241 comments='Added by kernelcare'

GET /msp/ignore_vuln.php action=restore qids=157849 ips=54.93.87.241 comments='Added by kernelcare'

# Delete dynamyc search
GET /api/2.0/fo/qid/search_list/dynamic/ action=delete ids=3034146

GET /api/2.0/fo/asset/ip/?action=list

GET /api/2.0/fo/asset/host/ action=list details=Basic ips=54.93.87.241 






